import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Head from "next/head";
import Container from "../src/components/Container";
import Header from "../src/components/Header";
import { Provider } from "react-redux";
import { store } from "../src/redux/Store";
import TermOfServices from "../src/components/termsOfServices/TermOfServices";
import Snackbars from "../src/components/notification/Snackbars";
import AssetsTable from "../src/components/asset/table/AssetsTable";
import Footer from "../src/components/footer/Footer";

export default function Home() {
  // Create a client
  const queryClient = new QueryClient();
  return (
    <Provider store={store}>
      <QueryClientProvider client={queryClient}>
        <>
          <Head>
            <title>Assets Page</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main>
            <TermOfServices />
            <Container>
              <>
                <Snackbars />
                <Header />
                <div className="container mx-auto overflow-auto mb-auto">
                  <AssetsTable />
                </div>
                <Footer />
              </>
            </Container>
          </main>
        </>
      </QueryClientProvider>
    </Provider>
  );
}
