import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Head from "next/head";
import Container from "../src/components/Container";
import Header from "../src/components/Header";
import { Provider } from "react-redux";
import { store } from "../src/redux/Store";
import TermOfServices from "../src/components/termsOfServices/TermOfServices";
import Snackbars from "../src/components/notification/Snackbars";
import AssetsTable from "../src/components/asset/table/AssetsTable";

export default function Home() {
  // Create a client
  const queryClient = new QueryClient();
  return (
    <Provider store={store}>
      <QueryClientProvider client={queryClient}>
        <>
          <Head>
            <title>Assets Page</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main>
            <TermOfServices />
            <Container>
              <>
                <Snackbars />
                <Header />
                <div className="container mx-auto overflow-auto ">
                  <AssetsTable />
                </div>
              </>
            </Container>
          </main>
          {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
        </>
      </QueryClientProvider>
    </Provider>
  );
}
