import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import dynamic from "next/dynamic";
import Head from "next/head";
import { Provider } from "react-redux";
import AssetsTable from "../src/components/asset/table/AssetsTable";
import Container from "../src/components/Container";
import { store } from "../src/redux/Store";

const Header = dynamic(() => import("../src/components/Header"));
const TermOfServices = dynamic(
  () => import("../src/components/termsOfServices/TermOfServices")
);
const Snackbars = dynamic(
  () => import("../src/components/notification/Snackbars")
);
const Footer = dynamic(() => import("../src/components/footer/Footer"));

export default function Home() {
  const queryClient = new QueryClient();
  return (
    <Provider store={store}>
      <QueryClientProvider client={queryClient}>
        <>
          <Head>
            <title>Assets Page</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main>
            <TermOfServices />
            <Container>
              <>
                <Snackbars />
                <Header />
                <div className="container mx-auto overflow-auto mb-auto">
                  <AssetsTable />
                </div>
                <Footer />
              </>
            </Container>
          </main>
        </>
      </QueryClientProvider>
    </Provider>
  );
}
